# Generated by Django 3.2.15 on 2023-11-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='fistname',
            new_name='firstname',
        ),
    ]
