# Generated by Django 3.2.15 on 2023-11-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20231129_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Н', 'Необработан'), ('Г', 'Готовится'), ('С', 'Сборка'), ('Д', 'Доставка'), ('В', 'Выполнен')], db_index=True, default='Н', max_length=1, verbose_name='статус заказа'),
        ),
    ]
