# Generated by Django 3.2.15 on 2023-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Н', 'Необработан'), ('Г', 'Готовится'), ('С', 'Сборка'), ('Д', 'Доставка'), ('В', 'Выполнен')], db_index=True, default='Н', max_length=1, verbose_name='Cтатус заказа'),
        ),
    ]
