# Generated by Django 3.2.15 on 2023-12-11 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20231203_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Э', 'Электронно'), ('Н', 'Наличностью'), ('Е', 'Не указано')], db_index=True, default='Н', max_length=1, verbose_name='Cпособ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Н', 'Необработан'), ('Г', 'Готовится'), ('С', 'Сборка'), ('Д', 'Доставка'), ('В', 'Выполнен')], db_index=True, default='Е', max_length=1, verbose_name='Cтатус заказа'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена в заказе'),
        ),
    ]
