# Generated by Django 3.2.15 on 2023-12-04 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Адрес')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('registered_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Координат места',
                'verbose_name_plural': 'Координаты места',
            },
        ),
    ]
