version: '3'
services:

  db:
    image: postgres:14.7-alpine
    container_name: sb_postgres
    volumes:
      - db_data:/var/lib/postgresql/data

    ports:
      - 5432:5432

  frontend:
    image: sb_frontend
    container_name: sb_frontend
    build: ../frontend
    volumes:
      - /home/lamerork/apps/star-burger-docker/staticfiles:/app/staticfiles

  backend:
    image: sb_backend
    container_name: sb_backend
    build: ../backend
    volumes:
      - /home/lamerork/apps/star-burger-docker/staticfiles:/app/staticfiles
      - /home/lamerork/apps/star-burger-docker/media:/app/media
    env_file:
      - .env
    command: gunicorn -w 3 -b 127.0.0.1:8080 star_burger.wsgi:application
    ports:
      - 8080:8080

    depends_on:
      - db
      - frontend

volumes:
  db_data:
